// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqaOlDrInfvZbgwt_GmMbkaCUzGeyCI7A',
    appId: '1:1005468576407:web:e06d7bd32d8650819097d2',
    messagingSenderId: '1005468576407',
    projectId: 'savebite-6b309',
    authDomain: 'savebite-6b309.firebaseapp.com',
    storageBucket: 'savebite-6b309.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2bZ6GpFv-rJLF-xFfjcvcwQ5oI3LDce8',
    appId: '1:1005468576407:android:ae21c809c27deec29097d2',
    messagingSenderId: '1005468576407',
    projectId: 'savebite-6b309',
    storageBucket: 'savebite-6b309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRWdnr2To8gB4hMH3w7_l4KxtzkNVowOk',
    appId: '1:1005468576407:ios:c9789f248a3735ad9097d2',
    messagingSenderId: '1005468576407',
    projectId: 'savebite-6b309',
    storageBucket: 'savebite-6b309.firebasestorage.app',
    iosBundleId: 'com.example.saveBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRWdnr2To8gB4hMH3w7_l4KxtzkNVowOk',
    appId: '1:1005468576407:ios:c9789f248a3735ad9097d2',
    messagingSenderId: '1005468576407',
    projectId: 'savebite-6b309',
    storageBucket: 'savebite-6b309.firebasestorage.app',
    iosBundleId: 'com.example.saveBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqaOlDrInfvZbgwt_GmMbkaCUzGeyCI7A',
    appId: '1:1005468576407:web:4e86fcd3c8904a389097d2',
    messagingSenderId: '1005468576407',
    projectId: 'savebite-6b309',
    authDomain: 'savebite-6b309.firebaseapp.com',
    storageBucket: 'savebite-6b309.firebasestorage.app',
  );
}
